title: Damián Muraña
author: Damián Muraña
email: damian@murana.uy
description: Blog de apuntes sobre tecnología, software libre, GNU/Linux, redes y otros temas de interés del autor.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Damián Muraña
  tagline: Geek. Software Libre.
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: dmurana
    github:  dmurana
    linkedIn: in/dmurana
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    telegram: dmurana
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    mastodon:
    - username: dmurana
      instance: mstdn.io
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - autor.md
